const users=[
    {
        id:1,
        name:'George',
        imgSrc:'./images/george.jpg',
        phoneNumber:'0896831628',
        email:'george@gmail.com',
    },
    {
        id:2,
        name:'Yoana',
        imgSrc:'./images/yoana.jpg',
        phoneNumber:'0896831622',
        email:'yoana@gmail.com',
    },
    {
        id:3,
        name:'Peter',
        imgSrc:'./images/peter.jpg',
        phoneNumber:'0896831623',
        email:'peter@gmail.com',
    },
    {
        id:5,
        name:'Petkana',
        imgSrc:'./images/petkana.jpg',
        phoneNumber:'0896831624',
        email:'steven@gmail.com',
    },
]